POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtyZW1sZXZtYTQ0eDMxIiwiaWQiOiI2MjYxMTU3ZGY1YWQ3N2ZjNmNmYjdiNDkiLCJpYXQiOjE2NTA1MzA5Mzl9.zzO3RDuoFRQW-bUqd8eXpR_ujVGSvlC_0EkL0F2T8is

{
  "title": "Blog 4",
  "author": "Max 4",
  "url": "www.maxtest4.com",
  "likes": "1231111"
}

###
DELETE http://localhost:3001/api/blogs/6261ff00555da5adcf18f654
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtyZW1sZXZtYTQ0eDMxIiwiaWQiOiI2MjYxMTU3ZGY1YWQ3N2ZjNmNmYjdiNDkiLCJpYXQiOjE2NTA1MzA5Mzl9.zzO3RDuoFRQW-bUqd8eXpR_ujVGSvlC_0EkL0F2T8is

###
GET http://localhost:3001/api/blogs/62567d779e71791ff995e361

###

POST http://localhost:3001/api/users/
Content-Type: application/json

{
 "name": "Max Kremlev",
 "username": "kremlevma44x31",
 "password": "1233331" 
}
  

###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
 "username": "kremlevma44x31",
 "password": "1233331" 
}