POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "title": "Blog 1",
  "author": "Max",
  "url": "www.max.com",
  "likes": "123"
}

###

DELETE http://localhost:3001/api/blogs/625f80cb9fdfbdaa858455a6

###
GET http://localhost:3001/api/blogs/62567d779e71791ff995e361

###

POST http://localhost:3001/api/users/
Content-Type: application/json

{
 "name": "Max Kremlev",
 "username": "kremlevmax",
 "password": "123333" 
}
  

###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
 "username": "kremlevmax",
 "password": "123333" 
}