POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWZiMTM0OGM0Nzk1OWMzZTE1YmZjMiIsImlhdCI6MTY1MDQ0ODI0NH0.rMRIRH0o9GKQ2mjlulGSlulkHlwQC4U5fxVI3ZcCApM

{
  "title": "Blog 7777",
  "author": "Max 77777",
  "url": "www.max5111677.com",
  "likes": "1231111"
}

###

DELETE http://localhost:3001/api/blogs/625fd7b932263cc1a056e10b
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWZiMTM0OGM0Nzk1OWMzZTE1YmZjMiIsImlhdCI6MTY1MDQ0ODI0NH0.rMRIRH0o9GKQ2mjlulGSlulkHlwQC4U5fxVI3ZcCApM

###
GET http://localhost:3001/api/blogs/62567d779e71791ff995e361

###

POST http://localhost:3001/api/users/
Content-Type: application/json

{
 "name": "Max Kremlev",
 "username": "kremlevmax1",
 "password": "1233331" 
}
  

###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
 "username": "kremlevmax",
 "password": "123333" 
}